# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 23:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20170714_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default="0", max_length=20),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='telerivet_time_created',
        ),
        migrations.AddField(
            model_name='contact',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_contacted',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_heard_from',
            field=models.DateTimeField(blank=True),
        ),
    ]
